# Generated by Django 4.2.30 on 2026-07-14 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('changed_on', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Nome de Atributo',
                'verbose_name_plural': 'Nomes de Atributo',
                'db_table': 'product_attribute_name',
            },
        ),
        migrations.CreateModel(
            name='ProductBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('changed_on', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'db_table': 'product_base',
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('changed_on', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'product_brand',
            },
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('changed_on', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('abbreviation', models.CharField(max_length=10, unique=True, verbose_name='Abreviação')),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
                'db_table': 'product_unit',
            },
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('changed_on', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('sku', models.CharField(max_length=50, unique=True, verbose_name='SKU')),
                ('barcode', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de barras')),
                ('attributes', models.JSONField(blank=True, default=dict, verbose_name='Atributos')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço de custo')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Preço de venda')),
                ('weight', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Peso')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.productbase', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Item de Produto',
                'verbose_name_plural': 'Itens de Produto',
                'db_table': 'product_item',
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('changed_on', models.DateTimeField(auto_now=True, verbose_name='Alterado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='product.productcategory', verbose_name='Categoria pai')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'product_category',
            },
        ),
        migrations.AddField(
            model_name='productbase',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.productbrand', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='productbase',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.productcategory', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='productbase',
            name='unit_of_measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.unitofmeasure', verbose_name='Unidade de Medida'),
        ),
    ]
